extends RefCounted

## Battle-local presentation overrides. Portrait defaults stay with their shared
## components; no theme, viewport, gameplay or persistent setting is changed.
const VALUES := {
	"column_gap": 36,
	"card_gap": 32,
	"card_text_scale": 1.5,
	"card_min_text_font": 88,
	"card_aspect": 1.85,
	"card_width_fraction": 0.21,
	"card_padding": 12.0,
	"card_info_gap": 20.0,
	"card_portrait_fraction": 0.43,
	"card_name_height": 144.0,
	"card_hp_number_height": 144.0,
	"card_hp_bar_height": 44.0,
	"card_status_height": 112.0,
	"card_info_separation": 24.0,
	"column_padding": 32.0,
	"board_height_padding": 16.0,
	"content_top_gap": 26.0,
	"header_height": 192.0,
	"header_font": 144,
	"header_button_size": Vector2(152, 152),
	"footer_height": 400.0,
	"footer_divider_height": 3.0,
	"protocol_font": 100,
	"protocol_button_size": Vector2(224, 224),
	"protocol_cost_font": 72,
	"protocol_stack_height": 224.0,
	"protocol_label_top": -208.0,
	"protocol_label_bottom": -96.0,
	"protocol_bar_height": 52.0,
	"protocol_group_gap": 24,
	"protocol_bar_max_width": 1800.0,
	"protocol_group_fraction": 0.90,
	"action_font": 80,
	# Compensates for the taller footer: ~1.6x projected size versus Stage B.
	"dice_camera_size": 7.04,
	"dice_center_gap": 64.0,
	"tag_slot_width_ratio": 1.10,
	"tag_wrap_before_shrink": true,
	"tag_side_gap": 16.0,
	"action_band_height": 168.0,
}
