"""Regenerate the inlined assets of the branded web loader in web/shell.html.

The loader must paint before the Godot runtime exists, and the web export
ships only the shell HTML itself, so its art is inlined as data URIs between
the LOADER-ASSETS markers. Everything is derived from the game's own assets:

  - O ring  : the reactor "O" cropped from assets/ui/logo_base.png
  - O core  : the matching glow layer from assets/ui/logo_core.png (the layer
              TitleLogo pulses in-game; the loader pulses it with CSS)
  - font    : assets/fonts/m5x7.ttf subset to the loader's glyphs

  python tools/web_loader_assets.py      (needs Pillow + fonttools)
"""
import base64
import io
import re
import subprocess
import sys
import tempfile
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
SHELL = ROOT / "web" / "shell.html"
# The O occupies x 8..328, y 8..329 of the 1588x504 logo layers and the V
# starts at x 335; this square crop keeps the O centred and excludes the V.
O_BOX = (2, 2, 334, 334)
O_SIZE = 240          # px; displayed at <= 220 CSS px, so this stays crisp at 1x
O_COLORS = 64         # palette PNG: the art is a small flat palette
FONT_TEXT = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789.,%!?-: "


def png_uri(path: Path) -> str:
    im = Image.open(path).convert("RGBA").crop(O_BOX).resize((O_SIZE, O_SIZE), Image.LANCZOS)
    buf = io.BytesIO()
    im.quantize(colors=O_COLORS, method=Image.Quantize.FASTOCTREE).save(buf, "PNG", optimize=True)
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def font_uri() -> str:
    with tempfile.TemporaryDirectory() as tmp:
        out = Path(tmp) / "m5x7_loader.ttf"
        subprocess.run([sys.executable, "-m", "fontTools.subset", str(ROOT / "assets/fonts/m5x7.ttf"),
                        f"--text={FONT_TEXT}", f"--output-file={out}", "--layout-features="],
                       check=True, capture_output=True)
        return "data:font/ttf;base64," + base64.b64encode(out.read_bytes()).decode("ascii")


def main() -> int:
    block = (
        "/* LOADER-ASSETS-BEGIN (generated by tools/web_loader_assets.py - do not hand-edit) */\n"
        "@font-face { font-family: 'm5x7-loader'; src: url('%s') format('truetype'); font-display: block; }\n"
        "#op-ring { background-image: url('%s'); }\n"
        "#op-core { background-image: url('%s'); }\n"
        "/* LOADER-ASSETS-END */"
    ) % (font_uri(), png_uri(ROOT / "assets/ui/logo_base.png"), png_uri(ROOT / "assets/ui/logo_core.png"))
    html = SHELL.read_text(encoding="utf-8")
    pattern = re.compile(r"/\* LOADER-ASSETS-BEGIN.*?LOADER-ASSETS-END \*/", re.S)
    if not pattern.search(html):
        print("web/shell.html has no LOADER-ASSETS markers", file=sys.stderr)
        return 1
    html = pattern.sub(lambda _m: block, html)
    SHELL.write_text(html, encoding="utf-8", newline="\n")
    print(f"[loader] inlined assets: {len(block) // 1024} KB into {SHELL.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
